### ISSUE TITLE
would you share the steps of creating the template?

### ISSUE THREAD

**Issue by jingkang99** [plihelix/wails-sveltekit#2]
sveltekit is great. I want to use it with wails too. thanks

**Comment by plihelix** [comment]
![wails-skeleton-setup](https://user-images.githubusercontent.com/73962193/210877024-916037dc-81d9-46e8-8fd4-119a407698e5.png)
![forms](https://user-images.githubusercontent.com/73962193/210877161-4c35e713-8598-403d-8584-380a10f3215f.png)
![theme](https://user-images.githubusercontent.com/73962193/210877229-66734cfe-a0be-4422-bfd6-dba59ee4ff21.png)
![running](https://user-images.githubusercontent.com/73962193/210877284-be3ef4eb-3d91-41cc-8de6-3553eba39581.png)

**Comment by plihelix** [comment]
Correction, after choosing typescript, feel free to chose what you want!
![skeleton](https://user-images.githubusercontent.com/73962193/210882517-64c8e0af-ee7a-4dae-b671-3bb46a8d0b2c.png)

**Comment by plihelix** [comment]
the a tags don't work by default, but you just have to remove the `target="{...}"` and they'll work.

**Comment by plihelix** [comment]
As I'm figuring out the details of this stack, rest assured a guide is coming.
In the mean time, I hope that the builder script is verbose and clear enough to read through in its place.

**Comment by plihelix** [comment]
Closing.
